AUTHOR0 = 'HPL'
AUTHOR1 = 'EAP'
AUTHOR2 = 'MWS'
AUTHORS_TAGS = {AUTHOR0, AUTHOR1, AUTHOR2}
AUTHOR_TO_INDEX = {
    AUTHOR0: 0,
    AUTHOR1: 1,
    AUTHOR2: 2
}

AUTHOR_TAG_CSV = "author"
TEXT_TAG_CSV = "text"
ID_TAG_CSV = "id"