
MODEL = "MODEL"
TRAIN_BATCH_SIZE = "TRAIN_BATCH_SIZE"
VALID_BATCH_SIZE = "VALID_BATCH_SIZE"
TRAIN_EPOCHS = "TRAIN_EPOCHS"
LEARNING_RATE = "LEARNING_RATE"
MAX_SOURCE_TEXT_LENGTH = "MAX_SOURCE_TEXT_LENGTH"
SEED = "SEED"
DROUPOUT = "DROUPOUT"
CHECKPOINT = "CHECKPOINT"
BERT = "BERT"
BETA_FOR_WEIGHTED_CLASS_LOSS = "BETA_FOR_WEIGHTED_CLASS_LOSS"
OUTPUT_DIR = "OUTPUT_DIR"

model_params_1 = {
    MODEL: "BERT",
    CHECKPOINT: "bert-base-cased",
    TRAIN_BATCH_SIZE: 32,
    VALID_BATCH_SIZE: 32,
    TRAIN_EPOCHS: 10,
    LEARNING_RATE: 3e-5,
    MAX_SOURCE_TEXT_LENGTH: 512,
    SEED: 42,
    DROUPOUT: 0.3,
    BETA_FOR_WEIGHTED_CLASS_LOSS: 0.9999,
    OUTPUT_DIR: "./output"
}